name: imageRec
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - flask=2.0.1
  - numpy>=1.19.5
  - opencv>=4.5.3
  - tensorflow-cpu>=2.5.0
  - pip
  - pip:
    - deepface>=0.0.75
    - gunicorn==20.1.0